name: caddy-docker

on:
  push:
    branches: [ main ]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: mycaddy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy:latest
      - name: Build and push for webdav
        uses: docker/build-push-action@v3
        with:
          context: caddy-webdav
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy:webdav
      - name: Build and push for webdav
        uses: docker/build-push-action@v3
        with:
          context: caddy-webdav-dnspod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy:webdav-dnspod
